name: Build and Publish Docker image

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  release:
    types: [published]
  pull_request: 
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses:  bitovi/github-actions-docker-publish
      with:
        docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repo_name: deploy-eks-helm

