name: Build and Publish Docker image

on:
  workflow_dispatch: {}
  push:
    branches: [ main, DevOps-110 ]
  #release:
   # types: [published]
  pull_request: 
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses:  bitovi/github-actions-docker-publish@DEVOPS-110
      with:
        repo_name: deploy-eks-helm
        use_latest: 'false'
